repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use a fixed version instead of a branch
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1 # Use a fixed version instead of a branch/moving tag
    hooks:
      - id: go-imports
      - id: go-critic
      - id: go-mod-tidy
      - id: go-unit-tests

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.53.3 # Use a fixed version
    hooks:
      - id: golangci-lint
