version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: url-shortener-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - url-shortener-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 20s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo-express:
    image: mongo-express:latest
    container_name: url-shortener-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - url-shortener-network
    restart: unless-stopped

networks:
  url-shortener-network:
    driver: bridge
