name: Go Lint & Test

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
      - name: Run pre-commit
        run: pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}

  build:
    name: Build Application
    needs: [pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          check-latest: true
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v -o url-shortener ./cmd/...
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: url-shortener
          path: url-shortener
          retention-days: 7
